version: 2
registries:
  composer-repository-nova-laravel-com:
    type: composer-repository
    url: https://nova.laravel.com
    username: michael@dyrynda.com.au
    password: "${{secrets.COMPOSER_REPOSITORY_NOVA_LARAVEL_COM_PASSWORD}}"

updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "19:30"
  open-pull-requests-limit: 10
  registries:
  - composer-repository-nova-laravel-com
